import { Command } from 'commander';
import fs from 'fs-extra';
import path from 'path';
import { loadConfig } from '../utils/config.js';
import { SessionData } from '../types.js';
import { ui } from '../ui/renderer.js';

export function reportCommand(): Command {
    const cmd = new Command('report');
    cmd.description('Generate a Markdown security report from a session')
        .option('--session <id>', 'Session ID')
        .option('--output <file>', 'Output file path')
        .action(async (options) => {
            const config = await loadConfig();
            let sessionPath: string;
            if (options.session) {
                sessionPath = path.join(config.sessionDir, options.session);
            } else {
                const dirs = (await fs.readdir(config.sessionDir)).sort().reverse();
                if (dirs.length === 0) { ui.error('No sessions found.'); process.exit(1); }
                sessionPath = path.join(config.sessionDir, dirs[0]);
                ui.info(`Using most recent session: ${dirs[0]}`);
            }
            const sessionFile = path.join(sessionPath, 'session.json');
            if (!(await fs.pathExists(sessionFile))) { ui.error('Session not found.'); process.exit(1); }
            const session = (await fs.readJson(sessionFile)) as SessionData;
            const report = generateReport(session);
            const outFile = options.output || path.join(sessionPath, 'report.md');
            await fs.writeFile(outFile, report, 'utf-8');
            ui.success(`Report saved: ${outFile}`);
        });
    return cmd;
}

function generateReport(session: SessionData): string {
    const s = session.summary;
    let md = `# Cortex Security Report\n\n**Target:** \`${session.target}\`  \n**Session:** \`${session.id}\`  \n**Date:** ${new Date(session.startedAt).toLocaleString()}\n\n---\n\n## Executive Summary\n\n${s?.aiNarrative || 'N/A'}\n\n---\n\n## Findings Overview\n\n| Severity | Count |\n|----------|-------|\n| 🔴 CRITICAL | ${s?.criticalCount || 0} |\n| 🟠 HIGH | ${s?.highCount || 0} |\n| 🟡 MEDIUM | ${s?.mediumCount || 0} |\n| 🔵 LOW | ${s?.lowCount || 0} |\n| **Total** | **${s?.totalFindings || 0}** |\n\n`;

    md += `## Attack Paths\n\n`;
    if (session.attackGraphs.length === 0) { md += '_No attack paths constructed._\n\n'; }
    else {
        for (const g of session.attackGraphs) {
            md += `### ${g.title}\n\n**Impact:** ${g.impact}  **Likelihood:** ${g.likelihood}  **Confidence:** ${g.confidence}%\n\n${g.narrative}\n\n`;
            for (const step of g.steps) md += `${step.step}. **${step.actor}** → ${step.action} → \`${step.target}\` → ${step.result}\n`;
            md += '\n---\n\n';
        }
    }

    md += `## Detailed Findings\n\n`;
    const order = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO'];
    for (const f of [...session.findings].sort((a, b) => order.indexOf(a.severity) - order.indexOf(b.severity))) {
        const badge = { CRITICAL: '🔴', HIGH: '🟠', MEDIUM: '🟡', LOW: '🔵', INFO: '⚪' }[f.severity] || '⚪';
        md += `### ${badge} [${f.severity}] ${f.title}\n\n**ID:** \`${f.id}\`  **Confidence:** ${f.confidence}%\n\n${f.description}\n\n**Fix:** ${f.remediation}\n\n---\n\n`;
    }

    md += `## Endpoints\n\n| Method | Path | Status | Flags |\n|--------|------|--------|-------|\n`;
    for (const ep of session.endpoints) md += `| ${ep.method} | \`${ep.path}\` | ${ep.statusCode || '-'} | ${ep.flags.join(', ') || '-'} |\n`;
    md += `\n---\n*Generated by Cortex CLI v0.1.0*\n`;
    return md;
}